name: bricked
description: "brick"
publish_to: 'none'
version: 0.5.7+6

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.33.0
  flutter_animate: ^4.5.2
  google_fonts: ^6.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  flame_audio: ^2.11.11
  vibration: ^3.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/audio/

flutter_native_splash:
  color: "#ffffff"
  image: assets/icons/splash.png
  android_12:
    color: "#ffffff"
    image: assets/icons/splash.png
